Drtii 1184
UKHomeOffice/drt-dashboard pull request #104
Opened 2023-03-15 13:34 UTC by ngu04

- moving filtering logic to slick query

2023-03-15 13:46 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/UserDao.scala
> +  def inactiveUserIndex(numberOfInactivityDays: Int): UserTable => Rep[Boolean] = (user: UserTable) =>
a clearer name could be `noActivitySinceDays`

2023-03-15 13:50 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/UserDao.scala
> +  def revokeUserIndex: UserTable => Rep[Boolean] = (user: UserTable) =>
I think this should also check there's been no activity since X days, where X is [number of days considered inactive] + [number of days after inactive email send we deactivate account], eg 90 + 7

2023-03-15 13:51 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/UserDao.scala
> +  def revokeUserIndex: UserTable => Rep[Boolean] = (user: UserTable) =>
A clearer name could be `accessShouldBeRevoked`

2023-03-15 13:56 UTC, richbirch requested changes
- We need tests around these queries
- Function name clarity

2023-03-15 14:02 UTC, ngu04 commented on src/main/scala/uk/gov/homeoffice/drt/db/UserDao.scala
> +  def revokeUserIndex: UserTable => Rep[Boolean] = (user: UserTable) =>
There are test around queries if you look at UserDaoSpec .  
Also there is update in table which clear out(make column empty) if there is activity by the user .

2023-03-16 09:11 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/UserDao.scala
> +      user.latest_login < new Timestamp(Instant.now().minusSeconds((numberOfInactivityDays + 7) * secondsInADay).toEpochMilli) &&
Shall we pass the `7` in as a parameter named `deativateAfterWarningDays`?

2023-03-16 09:18 UTC, richbirch approved these changes
Good stuff - might just be nice to pass the other currently hard coded 7 days in as a parameter

2023-03-16 10:38 UTC, merged