Drtii 1219
UKHomeOffice/drt-dashboard pull request #127
Opened 2023-07-03 10:30 UTC by ngu04

- Upload video file to s3 with training template markdown and file name to database

2023-07-03 13:15 UTC, richbirch requested changes
Looking good! Just some minor renaming/re-wording here and there

2023-07-03 13:15 UTC, richbirch commented on database_setup/training_data_table.sql
> +CREATE TABLE training_data_template
Just to rename these tables:
`feature_guide` & `feature_guide_view`

2023-07-03 13:15 UTC, richbirch commented on react/src/App.css
> +.page-container {
Could we start adding specific styles as `sx` properties on the react components?

2023-07-03 13:15 UTC, richbirch commented on react/src/App.tsx
> +                    <Route exact path="/trainingUpload">
`userGuideUpload`

2023-07-03 13:15 UTC, richbirch commented on react/src/components/Navigation.tsx
> +                    <MenuItem onClick={handleClose}><Link to="/trainingUpload">Training Uploads</Link></MenuItem> : ""}
`Feature Guides`

2023-07-03 13:15 UTC, richbirch commented on react/src/components/trainingUpload/MarkdownEditor.tsx
> +        <div className="page-container">
If you change the `div` to `Box` then you can use the `sx` property to specify css

2023-07-03 13:15 UTC, richbirch commented on react/src/components/trainingUpload/TrainingUploadFile.tsx
> +    const [video, setVideo] = useState<File | null>(null);
I think we normally use 2 spaces for indentation

2023-07-03 13:15 UTC, richbirch commented on react/src/components/trainingUpload/TrainingUploadFile.tsx
> +            <h1>Training Content form</h1>
`New Feature Guide`

2023-07-03 13:15 UTC, richbirch commented on react/src/components/trainingUpload/TrainingUploadFile.tsx
> +        error ? <div style={{marginTop: '20px' , color:'red'}}> Error uploading file <br/>
`There was a problem saving the feature guide`

2023-07-03 13:15 UTC, richbirch commented on react/src/components/trainingUpload/TrainingUploadFile.tsx
> +        uploaded ? <div style={{marginTop: '20px'}}> File Uploaded Successfully <br/>
`New feature guide successfully saved`

2023-07-03 13:15 UTC, richbirch commented on react/src/components/trainingUpload/TrainingUploadFile.tsx
> +                <label htmlFor="image">Training video file : </label>
`Feature demo video (webm format)`

2023-07-03 13:15 UTC, richbirch commented on react/src/components/trainingUpload/TrainingUploadFile.tsx
> +                <label htmlFor="text">Title : </label>
I think we can drop the colons after the label text

2023-07-03 13:15 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/TrainingUploadRoutes.scala
> +      path("uploadVideo") {
`uploadFeatureGuide`

2023-07-03 13:15 UTC, richbirch commented on src/main/resources/application.conf
> +  drt-data {
Probably don't need the `drt-data` level here as it the DRT app

2023-07-03 13:15 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/uploadTraining/TrainingData.scala
> +case class TrainingDataTemplate(id: Option[Int], uploadTime: Timestamp, fileName: Option[String], title: Option[String], markdownContent: String)
Let's put this class in the shared project in drt-lib so we only have one copy of it

2023-07-17 10:35 UTC, richbirch requested changes
A few things to tidy up, and some naming & indentation to fix to keep things consistent

2023-07-17 10:35 UTC, richbirch commented on react/package.json
> +    "@material-ui/icons": "^4.11.3",
I don't think we should be using a v4 version of mui icons when we're already importing the v5 versions

2023-07-17 10:35 UTC, richbirch commented on react/src/App.css
> +.markdown-preview {
I don't see this being used anywhere

2023-07-17 10:35 UTC, richbirch commented on react/src/App.tsx
> +                    <Route exact path="/userGuideUpload">
Can we keep the routes as kebab-case, ie with dashes for consistency, and name it `feature-guide-upload` as we've not used 'user guide' anywhere

2023-07-17 10:35 UTC, richbirch commented on react/src/components/featureGuide/DeleteComponent.tsx
> +            .then(data => {
This should be in the `handleResponse` function

2023-07-17 10:35 UTC, richbirch commented on react/src/components/featureGuide/DeleteComponent.tsx
> +    id: string | undefined;
Can we use 2 spaces for indentation to keep things consistent with existing files?

2023-07-17 10:35 UTC, richbirch commented on react/src/components/featureGuide/DeleteComponent.tsx
> +            <div>
We don't need any of these `<div>`s

2023-07-17 10:35 UTC, richbirch commented on react/src/components/featureGuide/FeatureGuideEdit.tsx
> +                        <div style={{marginTop: '20px', font: "Arial", fontSize: "16px"}}>
It would be good to move these styles into a theme if we don't already have a default one like in drt-v2

2023-07-17 10:35 UTC, richbirch commented on react/src/components/featureGuide/MarkdownEditor.tsx
> +        <textarea
Fix indentation

2023-07-17 10:35 UTC, richbirch commented on react/src/components/featureGuide/PreviewComponent.tsx
> +                                    <Grid item xs={12} sx={{
This can be moved to a the theme

2023-07-17 10:35 UTC, richbirch commented on react/src/components/featureGuide/PublishComponent.tsx
> +            axios.post('/guide/publishFeatureGuide/publish/' + props.id)
The publish part of this route is repeated, and usually you'd pass the id as form data with a post. So the route could be `/guide/published` with `{published: true}` or `{published: false}` as the form data

2023-07-17 10:35 UTC, richbirch commented on react/src/components/featureGuide/PublishComponent.tsx
> +    const handleConfirmDialog = () => {
If this only calls one function then it should probably be the function, and maybe its name could be `updatePublishState`

2023-07-17 10:35 UTC, richbirch commented on src/main/resources/application.conf
> +    prefix-folder = ${?S3_BUCKET_PREFIX_FOLDER}
Yeah I guess we unify this with what's there already, and rename the prefix so it's clear what it's being used for

2023-07-17 10:35 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/FeatureGuideDao.scala
> +  def insertWebmDataTemplate(fileName: String, title: String, markdownContent: String): Unit = {
Any reason this is named differently to the update function? Should it maybe be `insertFeatureGuide`?

2023-07-17 10:35 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/uploadTraining/FeatureGuideService.scala
> +  def insertWebmDataTemplate(fileName: String, title: String, markdownContent: String): Unit = {
`updateFeatureGuide`

2023-07-17 10:35 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/uploadTraining/S3Service.scala
> +  def getVideoFile(filename: String) = {
Yeah I think this can be replaced by the s3 downloader

2023-07-17 10:35 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/uploadTraining/S3Service.scala
> +  def uploadFile(source: Source[ByteString, Any], filename: String)(implicit ec: ExecutionContextExecutor, system: ActorSystem[Nothing]) = {
and this can be replaced with the s3 uploader

2023-07-18 08:32 UTC, ngu04 commented on react/src/components/featureGuide/FeatureGuideEdit.tsx
> +                        <div style={{marginTop: '20px', font: "Arial", fontSize: "16px"}}>
Looks like theme affect all the app . I will looking to see if I can fix for everywhere else need to do in separate ticket .

2023-07-18 09:01 UTC, richbirch requested changes
Nice! Just some more case fixes and a little code to remove

2023-07-18 09:01 UTC, richbirch commented on build.sbt
> +//      "software.amazon.awssdk" % "s3" % awsJava2SdkVersion,
Comment to remove

2023-07-18 09:01 UTC, richbirch commented on react/src/App.css
> -
Can you update your intellij settings to leave a new line at the end of files?

2023-07-18 09:01 UTC, richbirch commented on react/src/components/featureGuide/DeleteComponent.tsx
> +    id: string | undefined;
Another intellij setting to update so we use 2 spaces for indentation

2023-07-18 09:01 UTC, richbirch commented on react/src/components/featureGuide/PublishComponent.tsx
> +            axios.post('/guide/published/' + props.id, {published: true})
Instead of repeating the whole 9 lines of this axios call it would be good to set a variable: `const published = props.actionString === 'publish'`

2023-07-18 09:01 UTC, richbirch commented on react/src/components/featureGuide/PublishComponent.tsx
> +            <div>
Each of these `<div>`s only have one component in them so they can be removed

2023-07-18 09:01 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/FeatureGuideViewDao.scala
> +sealed trait FeatureGuideViewLike {
We're not passing `FeatureGuideViewRow` between front and back ends so we don't need the ReadWriters

2023-07-18 09:01 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/FeatureGuideRoutes.scala
> +    path("getFeatureVideos" / Segment) { filename =>
Can we use `kebab-case` for all the routes?

2023-07-18 10:59 UTC, richbirch approved these changes
Sick! Nice one!

2023-07-18 14:31 UTC, merged