Drtii 1238 seminar
UKHomeOffice/drt-dashboard pull request #150
Opened 2023-09-04 15:54 UTC by ngu04

Drtii 1238 :  Manage Seminar =>  Create, Edit , Delete and publish to be available in DRT for users to register the seminar .

2023-09-12 15:27 UTC, richbirch requested changes
Quite a bit of tidying to do
- A lot of code repetition that can be eliminated
- The react views be be refactored to readable
- A few things to rename fix

2023-09-12 15:27 UTC, richbirch commented on react/package.json
> +    "start": "react-scripts start",
We need to keep `--openssl-legacy-provider` for it to function with newer versions of node

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/CreateSeminar.tsx
> +    const formData = new FormData();
We don't need to use a `FormData`. You can just post an object with the fields in and it comes through as json

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/CreateSeminar.tsx
> +dayjs.extend(timezone);
Can we stick to using `moment` for dates & times? It defaults to using the browser's local timezone so no need to set it either

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/CreateSeminar.tsx
> +                </div> :
I think we could do with using breadcrumbs here for easier navigation. We've currently got `<h1>Create Seminar</h1>` repeated 3 times for different versions of the header.

I think `viewSeminars ?` should be the top most item here as that decides whether we're editing or viewing a list

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/CreateSeminar.tsx
> +                viewSeminars ? <ListSeminar setViewSeminars={setViewSeminars}/> :
In fact, the list of seminars should be in its own component and not included here. This component is called `CreateSeminar` so it shouldn't be deciding if we're creating or viewing a list, there should be a parent component for the seminar section, or it should be handled by the route we're currently at

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/DeleteSeminar.tsx
> +    const [confirmDelete, setConfirmDelete] = useState(false);
There's a neat react component you can use for confirmation messages - `Snackbar` (https://mui.com/material-ui/react-snackbar/)
Saves you from adding your own logic to pop up a dialog and handle it closing etc

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/DeleteSeminar.tsx
> +                <Dialog open={props.showDelete} onClose={handleCloseConfirmDialog}>
I can send you a reusable component for generic confirmation dialogues since we're using at least 3 different ones with the seminars

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/EditSeminar.tsx
> +                    <form onSubmit={handleSubmit}>
Most of this form is the same as the creation form. It should be possible to combine them into a single component to save all the repetition

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/ListSeminar.tsx
> +    ];
Let's not show header labels for these columns as they don't fit and so can't be read

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/ListSeminar.tsx
> +                            showRegisteredUser ?
This needs a quite a bit of refactoring so it's readable. We can create a reusable `ConfirmationDialogue` component rather than adding custom ones for publishing and deleting (I have a similar thing in another project but with an action - I can send you the code)

What you want here is a div containing:
 - the list
 - a confirmation dialogue for publishing
 - a confirmation dialogue for un-publishing
 - a confirmation dialogue for deleting

you then control the display of the dialogues by setting the `isOpen` state for the appropriate dialogue

The `EditSeminar` would be better as part of a route for editing rather than being nested in the list component

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/PublishSeminar.tsx
> +export function PublishSeminar(props: Props) {
This can be replaced by the generic confirmation dialogue

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/ListSeminar.tsx
> +        error ? <div style={{marginTop: '20px', color: 'red'}}> Errored for the task <br/>
The error message should probably say something like `There was a problem fetching the list of seminars. Please try reloading the page`

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/RegisteredUsers.tsx
> +        error ? <div style={{marginTop: '20px', color: 'red'}}> Errored for the task <br/>
Let's improve this error messge

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/RegisteredUsers.tsx
> +                        <RemoveRegisteredUser id={rowDetails?.seminarId}
Another one to be replaced with a generic component

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/RegisteredUsers.tsx
> +                            <div>
Move this up to be the top level component as with `ListSeminar`

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/ListSeminar.tsx
> +export function ListSeminar(props: Props) {
There are one or more seminars so it should be `ListSeminars`

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/RemoveRegisteredUser.tsx
> +export function RemoveRegisteredUser(props: Props) {
Replace with a generic component

2023-09-12 15:27 UTC, richbirch commented on react/src/components/seminar/ViewSeminar.tsx
> +        showDelete ? <DeleteSeminar id={props.id} showDelete={showDelete} setShowDelete={setShowDelete}
Replace with a generic component

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/DrtDashboardApp.scala
> +    seminarRegistrationScheduleFrequency = config.getInt("seminar-registration.schedule-frequency-minutes"),
Can we name these more descriptively? What is the user tracking schedule doing? If it's to check for dormant users then it can be named `dormantUsersCheckFrequency`.
Likewise, the seminar one could be `seminarRemindersCheckFrequency`

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/SeminarDao.scala
> +  def published: Rep[Boolean] = column[Boolean]("published")
`isPublished` would be less ambiguous

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/SeminarDao.scala
> +  def latestUpdateTime: Rep[Timestamp] = column[Timestamp]("latest_update_time")
`lastUpdatedAt` follows the `..At` naming convention

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/SeminarDao.scala
> +  def getSeminarsWithInNotifyDate(): Future[Seq[SeminarRow]] = {
`getSeminarsDueForNotifying`
Maybe pass in the dates so it's not hard coded and easy to see from where it's being called from

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/SeminarDao.scala
> +  def getSeminars(listAll: Boolean): Future[Seq[SeminarRow]] = {
again, let's have 2 functions:
`getSeminars` which returns all seminars
`getFutureSeminars` which returns all future seminars

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/SeminarDao.scala
> +  def insertSeminarForm(title: String, description: String, startTime: Timestamp, endTime: Timestamp, meetingLink: Option[String]): Future[Int] = {
`insertSeminar`

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/SeminarRegisterDao.scala
> +    val fourteenDaysBeforeSeminar = new Timestamp(seminarDate.getTime - sevenDaysMilliSeconds)
Maybe a more generic name here since it says 14, but it's actually 7

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/notifications/EmailNotifications.scala
> +    val icsFileLink = s"$protocol$portOrLocal/seminar/calendarInvite/${seminar.id.getOrElse("")}"
The ics file will have to be served from the dashboard app rather than hard coding it to be from LHR as only users with access to LHR will be able to access it

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/SeminarRegisterRoutes.scala
> +      routeResponse(seminarRegisterDao.getRegisterUsers(seminarId).map(forms => complete(StatusCodes.OK, forms.toJson)), "Getting Seminar Forms")
Maybe `Getting registered seminar users`?

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/SeminarRoute.scala
> +            routeResponse(seminarDao.updateSeminar(SeminarRow(Some(seminarId.toInt), title, description, stringToTimestamp(startTime), stringToTimestamp(endTime), false, Option(meetingLink), new Time
can we extract the `routeResponse` arguments so we can see what's being sent to it?

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/SeminarRoute.scala
> +              .map(_ => complete(StatusCodes.OK, s"Seminar with Id $seminarId is updated successfully")), "Updating Seminar Form")
Maybe `Editing seminar`?

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/SeminarRoute.scala
> +      routeResponse(seminarDao.getSeminars(listAll.toBoolean).map(forms => complete(StatusCodes.OK, forms.toJson)), "Getting Seminar Forms")
Maybe `Getting seminars`?

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/SeminarRoute.scala
> +  def saveForm(seminarDao: SeminarDao)(implicit ec: ExecutionContext) = path("save") {
`saveSeminar`

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/SeminarRoute.scala
> +              .map(_ => complete(StatusCodes.OK, s"Seminar $title is saved successfully")), "Saving Seminar Form")
`Saving seminar`

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/schedule/SeminarReminder.scala
> +        logger.info(s"Unknown command to log")
`Unknown command: $unknown`

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/services/SeminarService.scala
> +  def usersToRemind(notifications: EmailNotifications)(implicit ec: ExecutionContext) = {
Add a return type

2023-09-12 15:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/services/SeminarService.scala
> +  def usersToRemind(notifications: EmailNotifications)(implicit ec: ExecutionContext) = {
Wait a second. This sends the reminders - the name suggests it returns a list of users to remind!
`sendSeminarReminders` would be a better name

2023-09-12 17:02 UTC, ngu04 commented on react/package.json
> +    "start": "react-scripts start",
my local node is v19.7.0 . I see following error with it 

>  ~/node/19.7.0/bin/node: bad option: --openssl-legacy-provider
> error Command failed with exit code 9.

2023-09-13 07:59 UTC, richbirch commented on react/package.json
> +    "start": "react-scripts start",
Ah my bad. It's needed for v18 (LTS). I've not tried v19

2023-09-15 07:40 UTC, richbirch commented on react/src/components/seminar/CreateSeminar.tsx
> +                <Box>
2 things with this:
 1. When the form saves successfully we can use the snackbar as a notification and take them straight back to the list. No need to display a message here on its own
 2. When there's an issue saving the form we should retain the form below the message so they can try submitting again

That would simplify this component as it would always display the form, and would only display the error message if there's an issue saving it

2023-09-15 07:53 UTC, richbirch commented on react/src/components/seminar/DialogActionComponent.tsx
> +export function DialogActionComponent(props: Props) {
This is great! If it were me then I would go a step further and make it truly generic by removing any seminar specific things and the post & delete stuff

2023-09-15 07:56 UTC, richbirch commented on react/src/components/seminar/EditSeminar.tsx
> +                    <form onSubmit={handleSubmit}>
Same thing here - the form should remain visible in the case of an error, and the on success the user should be redirected to the list with a snackbar success message

2023-09-15 07:59 UTC, richbirch commented on react/src/components/seminar/ListSeminars.tsx
> +                                       actionString='remove seminar'
Rather than passing the action method and the action url, you could pass a function to call when the confirm button is pressed in the dialogue. That would mean it's reusable throughout the app

2023-09-15 08:00 UTC, richbirch commented on react/src/components/seminar/RegisteredUsers.tsx
> +                <h2>User registered for seminar {props.seminarTitle}</h2>
`Users` &  `seminars`, ie plural. Or `Seminar registrations`

2023-09-15 08:07 UTC, richbirch commented on react/src/components/seminar/SeminarLanding.tsx
> +export function SeminarLanding() {
We shouldn't need any variables to decide which section the user is in

The add & edit pages would be via routes, eg `/seminars/edit/:id` & `/seminars/new`, and the first thing a user sees when going to the 'manage seminars' section is the list of seminars, with a button above it to add/create a new one

2023-09-15 08:09 UTC, richbirch commented on react/src/components/seminar/ViewSeminar.tsx
> +        <div>
No need for this div around the dialog

2023-09-15 08:10 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/SeminarDao.scala
> +  def latestUpdatedAt: Rep[Timestamp] = column[Timestamp]("latest_updated_at")
`lastUpdatedAt`

2023-09-15 08:14 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/SeminarRegisterDao.scala
> +  def removeUser(seminarId: String, email: String): Future[Int] = {
`removeRegisteredUser` - for consistency

2023-09-15 08:15 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/SeminarRegisterDao.scala
> +  def getUsersToNotify(seminarId: String, seminarDate: Timestamp): Future[Seq[SeminarsRegistrationRow]] = {
`getRegisteredUsersToNotify` for consistency

2023-09-15 08:17 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/SeminarRegisterRoutes.scala
> +  def removeUser(seminarRegisterDao: SeminarRegisterDao)(implicit ec: ExecutionContext) =
`removeRegisteredUser` - for consistency & clarity

2023-09-15 08:20 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/SeminarRoute.scala
> +  def editSeminar(seminarDao: SeminarDao)(implicit ec: ExecutionContext) = path("edit" / Segment) { seminarId =>
I think it should be `updateSeminar`, with the path being `"update" / Segment`

2023-09-15 08:23 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/schedule/SeminarReminder.scala
> +        serverConfig.seminarRemindersCheckFrequency.minutes,
we don't need to pass this separately if we're already passing serverConfig

2023-09-15 08:24 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/schedule/SeminarReminder.scala
> +        serverConfig.seminarRemindersCheckFrequency.minutes,
Actually, `serverConfig` and `maxSize` are not used so can be removed

2023-09-15 08:25 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/services/SeminarService.scala
> +            .getUsersToNotify(id.toString, seminar.startTime))
I think this would read easier if it was on one line

2023-09-15 08:42 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/notifications/EmailNotifications.scala
> +  def sendSeminarReminderEmail(email: String, anyPort: String, seminar: SeminarRow, isSecure: Boolean, baseDomain: String, teamEmail: String) = {
`anyPort`, `isSecure` & `baseDomain` are no longer used so can be removed

2023-09-15 08:43 UTC, richbirch requested changes
Much improved - nice one!
Just a few things to tidy up now, including using routing for the seminar pages - list, edit & new
Some naming improvements to keep things really clear and consistent

2023-09-18 13:27 UTC, richbirch requested changes
Nearly there mate!
Some things to fix for the user experience
We also should have a breadcrumb at the top of each seminar page so it's easy to see where you are:
 - Seminars
 - Seminars | Create
 - Seminars | Edit
 - Seminars | DRT tour | registrations

2023-09-18 13:27 UTC, richbirch commented on react/src/components/DialogComponent.tsx
> +            </Snackbar>
Do you think the snackbars maybe belong in the `DialogActionComponent`? The display of them is not handled in this component

2023-09-18 13:27 UTC, richbirch commented on react/src/components/seminar/EditSeminar.tsx
> +        setRedirectTo('/seminars/list');
Might be clearer to put this route (`/seminars/list`) in the `<Redirect` tag and use `redirectTo` as a boolean flag

2023-09-18 13:27 UTC, richbirch commented on react/src/components/seminar/ListSeminars.tsx
> +            field: 'isPublished',
None of the column headings can be read because they're too long for the short columns. If the icons are self explanatory then we don't need the headings:
 - published
 - view
 - delete
 - edit
 - users

2023-09-18 13:27 UTC, richbirch commented on react/src/components/seminar/ListSeminars.tsx
> +            field: 'id',
Don't think the ID is relevant to the end user

2023-09-18 13:27 UTC, richbirch commented on react/src/components/seminar/ListSeminars.tsx
> +            headerName: 'Latest Time',
If we're keeping this column it could be named `Updated`

2023-09-18 13:27 UTC, richbirch commented on react/src/components/seminar/ListSeminars.tsx
> +            <h1>Seminar List | <Link to={`/seminars/list/`+!showAll}>{showAll ? "Ahead Only" : "View all"}</Link></h1>
It would be clearer for the end user if we had radio buttons to select whether to `view all` or `upcoming` seminars

2023-09-18 13:27 UTC, richbirch commented on react/src/components/seminar/RegisteredUsers.tsx
> +        setRedirectTo('/seminars/list');
This redirect route could go straight in the `<Redirect` tag for clarity

2023-09-18 13:27 UTC, richbirch commented on react/src/components/seminar/CreateSeminar.tsx
> +                <Snackbar
I think the default anchor is possibly easier to see than at the bottom

2023-09-18 13:27 UTC, richbirch commented on react/src/components/seminar/CreateSeminar.tsx
> +    const handleSubmit = (e: React.FormEvent) => {
We need some validation before trying the post data that might not have been filled in

2023-09-18 13:27 UTC, richbirch commented on react/src/components/seminar/CreateSeminar.tsx
> +                <Snackbar
The expected behaviour on saving an item would be to immediately be taken back to the list and have the snackbar message displayed there. It feels a bit weird being redirected after the message has disappeared

2023-09-18 13:27 UTC, richbirch commented on react/src/components/seminar/ViewSeminar.tsx
> +            <Dialog open={props.view} maxWidth="sm" onClose={handleViewClose}>
Double indentation here

2023-09-19 08:07 UTC, ngu04 commented on react/src/components/seminar/CreateSeminar.tsx
> +    const handleSubmit = (e: React.FormEvent) => {
There are field which are required and it give error if there are no values provided

2023-09-19 08:08 UTC, ngu04 commented on react/src/components/seminar/CreateSeminar.tsx
> +                <Snackbar
Default is going bottom left . Not sure it is looking better . May be can try top ?

2023-09-19 08:08 UTC, ngu04 commented on react/src/components/seminar/RegisteredUsers.tsx
> +        setRedirectTo('/seminars/list');
<Redirect tag here is not working .

2023-09-19 08:12 UTC, ngu04 commented on react/src/components/seminar/ListSeminars.tsx
> +            <h1>Seminar List | <Link to={`/seminars/list/`+!showAll}>{showAll ? "Ahead Only" : "View all"}</Link></h1>
I have add checkbox with `view previous seminar` . It is looking better .  We can get comment in planning over it .

2023-09-19 10:26 UTC, richbirch approved these changes
Nice work dude!

2023-09-19 10:26 UTC, richbirch commented on react/src/components/DialogComponent.tsx
> +    confirmAction: boolean;
This isn't needed anymore

2023-09-19 10:26 UTC, richbirch commented on react/src/components/seminar/CreateSeminar.tsx
> +                <Snackbar
ah sorry, when i've used it in the past it's come up at the top. i think it's more visible at the top personally

2023-09-21 08:09 UTC, merged