Drtii 1316 feedback
UKHomeOffice/drt-dashboard pull request #178
Opened 2023-12-04 14:36 UTC by ngu04

- Implementing Feedback form using Formik 
- Api endpoint for feedback

2023-12-05 11:22 UTC, richbirch requested changes
Nice work!
A few things to fix and tidy up
It would also be worth you reading up on redux. You could easily split the form into separate pages with their own route if the question state was stored using redux. That would be easier to work with than a 400 line component

2023-12-05 11:22 UTC, richbirch commented on database_setup/ab_feature.sql
> +    test_type     text,
`test_type` could be `ab_version`, ie we talk about whether a user is seeing version A or version B of some content

2023-12-05 11:22 UTC, richbirch commented on database_setup/user_feedback.sql
> +    a_or_b_test text,
this is probably also clearer as `ab_version`

2023-12-05 11:22 UTC, richbirch commented on react/src/App.tsx
> +          <Route path={"/feedback/:feedbackType/:aORbTest"} element={<FeedbackForms/>}/>
maybe `:abVersion`

2023-12-05 11:22 UTC, richbirch commented on react/src/components/feedback/FeedbackForms.tsx
> +              value={values.question4}
Question 4 displays the answer to question 3 - I assume question 4's value must be incorrectly getting set when question 3 is submitted

2023-12-05 11:22 UTC, richbirch commented on react/src/components/feedback/FeedbackForms.tsx
> +                    variant="outlined">Continue</Button>
This final question's button should say `Submit feedback`

2023-12-05 11:22 UTC, richbirch commented on react/src/components/feedback/FeedbackList.tsx
> +  };
I'm not sure we need this. The button can just be a link to the download url that opens in a new tab

2023-12-05 11:22 UTC, richbirch commented on react/src/services/ApiClient.ts
> +  public static saveFeedBacksEndpoint = "/api/feedback/save";
To be RESTful, there should just be one url `/api/feedback`
The routes should respond according to the request type, ie:
- GET = list of feedback responses
- POST = save new feedback response

2023-12-05 11:22 UTC, richbirch commented on react/src/components/feedback/FeedbackList.tsx
> +      <Typography color="text.primary">User Feedbacks</Typography>
`User feedback responses`

2023-12-05 11:22 UTC, richbirch commented on react/src/components/feedback/FeedbackList.tsx
> +      <Button startIcon={<FileDownloadIcon/>} onClick={handleDownload}>Download Feedbacks</Button>
`Download feedback responses`

2023-12-05 11:22 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/FeedbackRoutes.scala
> +  def exportFeedback(feedbackDao: UserFeedbackDao)(implicit ec: ExecutionContext) = path("export") {
execution context isn't used in this function

2023-12-05 11:22 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/FeedbackRoutes.scala
> +  val formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss")
Can we add the return type to all public functions and values, and set private where appropriate as per intellij's suggestions?

2023-12-05 11:22 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/FeedbackRoutes.scala
> +      val csvHeader: String = "Email,ActionedAt,FeedbackAt,CloseBanner,FeedbackType,BfRole,DrtQuality,DrtLikes,DrtImprovements,ParticipationInterest,AOrBTest"
What are ActionedAt & FeedbackAt? They appear to contain the same value. Should FeedbackAt be CreatedAt?

The column headings can have spaces in them to make them more readable:
`"Email,Actioned at,Created at,Banner closed,Type,BF Role,Drt Quality,Likes,Improvements,Participation Interest?,AB version"

2023-12-05 11:22 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/FeedbackRoutes.scala
> +      concat(saveFeedback(feedbackDao) ~ getFeedbacks(feedbackDao) ~ exportFeedback(feedbackDao))
tilde `~` means concat, so you don't need to wrap in `concat` as well, or you use `concat` and pass each route as comma separated values

2023-12-05 11:22 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/FeedbackRoutes.scala
> +  def getFeedbacks(feedbackDao: UserFeedbackDao)(implicit ec: ExecutionContext) = path("all") {
let's drop the `all` & `save` paths to make it a restful endpoint

2023-12-05 11:22 UTC, richbirch commented on src/test/scala/uk/gov/homeoffice/drt/routes/FeedbackRoutesSpec.scala
> +        userFeedback.size === 2  && response.contains(s"Feedback from user $email is saved successfully")
Shouldn't there only be one row returned if we've only saved one set of feedback?

Also, if you drop the `check {` to a new line then intellij will intent the block correctly

2023-12-05 11:22 UTC, richbirch commented on react/src/components/feedback/FeedbackForms.tsx
> +              onClick={() => window.close()}
`window.close` gives an error `Scripts may close only the windows that were opened by them.`
So we may want to remove the button and just say something like 'You may now close this window'

2023-12-05 11:22 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/FeedbackRoutes.scala
> +      val toCsvString: UserFeedbackRow => String = feedback => s"${feedback.email}," +
You should either use a CSV library to create the rows properly, or make sure you wrap all content with quotes so that commas in the answers don't break the CSV (they do at the moment)

2023-12-05 14:26 UTC, ngu04 commented on react/src/components/feedback/FeedbackList.tsx
> +  };
This is because ,I also wanted to  setRequestedAt(moment().valueOf()) when button is click . Didn't find option to update state with Link so went with this one

2023-12-05 14:35 UTC, ngu04 commented on src/main/scala/uk/gov/homeoffice/drt/routes/FeedbackRoutes.scala
> +      val csvHeader: String = "Email,ActionedAt,FeedbackAt,CloseBanner,FeedbackType,BfRole,DrtQuality,DrtLikes,DrtImprovements,ParticipationInterest,AOrBTest"
Initially I thought keep close banner as separate date but later added flag . So you are correct in identifying we only need one date with closing flag .

2023-12-05 14:48 UTC, ngu04 commented on src/test/scala/uk/gov/homeoffice/drt/routes/FeedbackRoutesSpec.scala
> +        userFeedback.size === 2  && response.contains(s"Feedback from user $email is saved successfully")
expecting 1 but looks like drop and create table is not deleting rows from previous test

2023-12-05 14:56 UTC, ngu04 commented on react/src/components/feedback/FeedbackForms.tsx
> +              value={values.question4}
Value is not set in state so it is not reflected in saved  form  .I think is browser which is keeping data in textbox from previous question . let me see if I can explicit make browser to clear it.

2023-12-06 12:19 UTC, richbirch commented on react/src/components/feedback/FeedbackList.tsx
> +  };
This works:
```

      <Button
        startIcon={<FileDownloadIcon/>}
        component={MuiLink}
        href={`${ApiClient.feedBacksEndpoint}/export`}
        target={'_blank'}
        onClick={() => setRequestedAt(moment().valueOf())}
      >
        Download feedback responses
      </Button>
      ```

2023-12-06 12:24 UTC, richbirch commented on src/test/scala/uk/gov/homeoffice/drt/routes/FeedbackRoutesSpec.scala
> +        userFeedback.size === 2  && response.contains(s"Feedback from user $email is saved successfully")
I think it's worth figuring out why the tables aren't cleared between tests else the tests aren't going to be a true reflection of what's happening

2023-12-06 12:30 UTC, richbirch requested changes
Nice one.
Just remaining:
- that download link to fix (a solution in the comments)
- fix the tests not clearing the db table
- csv headers with spaces between words to make easier to read

2023-12-06 12:30 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/FeedbackRoutes.scala
> +      val csvHeader: String = "Email ,CreatedAt ,CloseBanner ,FeedbackType ,BfRole ,DrtQuality ,DrtLikes ,DrtImprovements ,ParticipationInterest ,ABVersion"
I meant add spaces between the words in each column so that they're easier to read in a spreadsheet :)
eg `Email,Created at,Feedback type,BF Role...`

2023-12-08 10:09 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/FeedbackRoutes.scala
> +      val csvHeader: String = "Email ,Created at ,Feedback type ,Bf role ,Drt quality ,Drt likes ,Drt improvements ,Participation interest ,AB version"
Technically there shouldn't be any whitespace either side of a comma

2023-12-08 10:10 UTC, richbirch approved these changes
Nice - let's just remove the additional white space in the column headers (the ones before or after a comma)

2023-12-08 12:27 UTC, merged