Drtii 831 upload and process
UKHomeOffice/drt-dashboard pull request #22
Opened 2021-06-25 09:06 UTC by ngu04

- Nebo upload page
- Process file endpoint with akka stream
- Convert to json and post to DRT using akka-client

2021-06-25 09:26 UTC, richbirch commented on .gitignore
> +.DS_Store
It looks like the .DS_Store file already got committed. Could you remove it from git?

2021-06-25 09:38 UTC, richbirch commented on react/src/App.tsx
> +                            <Home config={this.state.config !!} user={this.state.user !!}/>
What are the `!!` for here? Googling tells me it's to convert an object into a boolean value, but that's when it's placed at the front of the object. It looks like they're maybe not doing anything

2021-06-25 09:43 UTC, richbirch commented on react/src/App.tsx
> +                            <Home config={this.state.config !!} user={this.state.user !!}/>
If you drop the check for undefined then it'll also catch the null value whilst being a little shorter
```
{this.state.config && this.state.user ?
  <Home config={this.state.config} user={this.state.user}/> :
  <Loading/>
}
```

2021-06-25 09:59 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/DrtClient.scala
> +  def createDrtNeboRequest(data: List[FlightData], uri: String) = {
can you add the return type definition for this function?

2021-06-25 10:09 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/IndexRoute.scala
> +  def indexRouteDirectives(path: String = ""): Route = {
Can we change this string parameter to a neater implementation?
Maybe a new function that adds the redirection and common code factored out and shared? Or even just passing an object rather than a string. It feels better to use a new function as the behaviour is specific to this route

2021-06-25 10:13 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/UploadRoutes.scala
> +            fileUpload("csv") {
Might be worth putting this in a function to avoid the 10 levels of indentation and make it a little more readable

2021-06-25 10:14 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/UploadRoutes.scala
> +  def convertByteSourceToFlightData(metadata: FileInfo, byteSource: Source[ByteString, Any])(implicit ec: ExecutionContextExecutor, mat: Materializer) = {
Add the return type

2021-06-25 10:23 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/UploadRoutes.scala
> +    dataRows.groupBy(_.arrivalPort)
You can extract the tuples to readable variables to make it easier to see what's going on:

```
    dataRows.groupBy(_.arrivalPort)
      .flatMap { case (arrivalPort, portRows) =>
        portRows.groupBy(_.flightCode)
          .map { case (flightCode, flightRows) =>
            FlightData(arrivalPort, flightCode, covertDateTime(flightRows.head.date), flightRows.size)
          }
      }.toList```

2021-06-25 10:31 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/UploadRoutes.scala
> +                        convertByteSourceToFlightData(metadata, byteSource), _, httpClient))))(response => complete(s"Posted to DRT with status ${response.map(r => r._1 -> r._2)}"))
Can we change the `complete` message to something more meaningful? I'm not sure what the status means and can't work it out from `r._1 -> r._2`
Also, what is `response` in this context?

2021-06-25 10:36 UTC, richbirch commented on src/test/scala/uk/gov/homeoffice/drt/routes/UploadRoutesSpec.scala
> +        responseAs[String] shouldEqual """Posted to DRT with status List((lhr,202 Accepted))"""
See previous comment about making `List((lhr,202 Accepted))` more meaningful

2021-06-25 10:38 UTC, richbirch requested changes
Really good work mate. A few bits to tidy up, and some other suggestions, but very nice overall

2021-06-25 11:07 UTC, ngu04 commented on react/src/App.tsx
> +                            <Home config={this.state.config !!} user={this.state.user !!}/>
I think autoformat has done that . Change were not done by me here .

2021-06-25 11:29 UTC, richbirch commented
Oh yes! It's Mr Eppel to blame for this one :)

On Fri, 25 Jun 2021 at 12:07, Nilesh Gupta ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In react/src/App.tsx
> <https://github.com/UKHomeOffice/drt-dashboard/pull/22#discussion_r658683144>
> :
>
> > @@ -87,7 +87,7 @@ export default class App extends React.Component<IProps, IState> {
>                      <Route exact path="/">
>                          {this.state.config === undefined || this.state.user === undefined ?
>                              <Loading/> :
> -                            <Home config={this.state.config !!} user={this.state.user !! }/>
> +                            <Home config={this.state.config !!} user={this.state.user !!}/>
>
> I think autoformat has done that . Change were not done by me here .
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/UKHomeOffice/drt-dashboard/pull/22#discussion_r658683144>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHAJJSK2VZTAXZAX6M4KU3TURPPRANCNFSM47JPOA2Q>
> .
>

2021-06-28 13:15 UTC, richbirch approved these changes
wicked! :robot:

2021-06-28 13:18 UTC, merged