Drtii 1038
UKHomeOffice/drt-dashboard pull request #72
Opened 2022-08-25 08:00 UTC by ngu04

- Choosing between RCCU and Ports selection and more information collection from user before requesting access for DRT port or regions

2022-08-25 10:34 UTC, richbirch requested changes
Nice job! A few bits of tidying but looking good :)

2022-08-25 10:34 UTC, richbirch commented on react/src/components/AccessRequestForm.tsx
> +    const moreInfoConditionCheck = () => {
`moreInfoConditionCheck` could be more descriptive. For example `moreInfoRequired`

2022-08-25 10:34 UTC, richbirch commented on react/src/components/AccessRequestForm.tsx
> +                {moreInfoConditionCheck() && state.lineManager.length > 4 && state.agreeDeclaration ?
We might want to add an email address validation function to the line manager field, and if it's not valid we should display an appropriate message next to the text input so that the user knows why the submit button isn't enabled

2022-08-25 10:34 UTC, richbirch commented on react/src/components/AccessRequestForm.tsx
> +                {moreInfoConditionCheck() && state.lineManager.length > 4 && state.agreeDeclaration ?
We should display a disabled submit button until they've met the form requirements rather than hide it

2022-08-25 10:34 UTC, richbirch commented on react/src/components/AccessRequestForm.tsx
> +                        Request access
Can we move the submit button out of `AccessRequestFormModal` so that we only have one button? The modal form can be triggered when the button is clicked depended on whether more info it needed or not

2022-08-25 10:34 UTC, richbirch commented on react/src/components/AccessRequestFormModal.tsx
> +export default function AccessRequestFormModal(props: IProps) {
`AccessRequestFormModal` might be clearer as something like `AccessRequestAdditionalInformationForm`

2022-08-25 10:34 UTC, richbirch commented on react/src/components/PortsByRegionCheckboxes.tsx
> +    const updateByRegionSelection = (region: string) => {
`updateByRegionSelection` - remove the 'By' -> `updateRegionSelection`

2022-08-25 10:34 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/notifications/EmailNotifications.scala
>          "5f34d7bb-293f-481c-826b-62661ba8a736",
Would be nice to extract these template ids to vals with a descriptive name now we have more than one, just to make it clear that they're specific templates

2022-08-25 14:54 UTC, ngu04 commented on react/src/components/AccessRequestForm.tsx
> +                        Request access
Model can be triggered when user click button but I think once user fill the form in model  they need something to click saying they are done .  Maybe we can rename it 'Request submit' to 'Done' ?

2022-08-26 07:51 UTC, richbirch commented on react/src/components/AccessRequestForm.tsx
> +    const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
`handleChange` is quite vague. How about `handleEmailChange`

2022-08-26 09:36 UTC, richbirch approved these changes
:boom:

2022-08-26 09:38 UTC, merged