Drtii 1034 1
UKHomeOffice/drt-dashboard pull request #76
Opened 2022-10-10 10:31 UTC by ngu04

User request access as part for user management 
- showing user requested for access 
- approval process 
- showing approval list of user
- user access details on row click

2022-10-10 13:16 UTC, richbirch requested changes
Good stuff! A bit of tidying and naming improvements. And a lot of typescript fixes to make

2022-10-10 13:16 UTC, richbirch commented on build.sbt
> +//      "org.slf4j" % "slf4j-nop" % "1.7.26",
remove commented line

2022-10-10 13:16 UTC, richbirch commented on database_setup/aggregated-user_access_requests.sql
> +  staffing boolean NOT NULL,
can we rename this to `staff_editing` to allow us to introduce a view-only `staffing` permission later?

2022-10-10 13:16 UTC, richbirch commented on database_setup/aggregated-user_access_requests.sql
> +  rcc_option boolean NOT NULL,
Could we change this to something like `account_type` where it would be either 'port' or 'rccu'? This way we can easily add 'national' later without adding a new field

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +    const [count, setCount] = React.useState(0);
Can we give `count` a meaningful name?

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +    const addUserToGroups = () => {
I think the action here should be `approveUserAccessRequest`. Adding the user to various groups is an implementation detail

2022-10-10 13:16 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/ApiRoutes.scala
> +        (get & path("userDetails" / Segment)) { userEmail =>
can we keep to the 'kebab-case' convention for the end point names rather than introducing camelCase?

2022-10-10 13:16 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/ApiRoutes.scala
> +        (post & path("addUserToGroup" / Segment)) { id =>
This end point should be `accept-user-request` as this is the desired behaviour - the endpoint doesn't know anything about groups

2022-10-10 13:16 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/ApiRoutes.scala
> +        (get & path("request-access")) {
I think this route should be `access-request` as that's what it's returning rather than a `request access` is a very, so suggests it's doing something rather than fetching access request details

2022-10-10 13:16 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/notifications/EmailNotifications.scala
> +  def sendAccessGranted(requester: String) = {
can we add a bcc to the drt poise email address so that we can see the emails being sent out to users for a while?

2022-10-10 13:16 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/UserAccessRequestDao.scala
> +  staffing: Boolean,
let's rename this to `staff_editing`

2022-10-10 13:16 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/UserAccessRequestDao.scala
> +  rccOption: Boolean,
can this be an `accountType` string, ie 'port' or 'region'

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +        let fond = selectedRows.map(s => findEmail(s))
shall we remove the `fond` (typo?) variable and just add a call to keyCloakUserDetails to the first map?

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +    const [approvedUserRequest, setApprovedUserRequest] = React.useState(false)
We can improve the naming here. `showApprovedRequests` would be clearer as to its purpose

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +        console.log('keyCloakUserDetails email ' + ApiClient.userDetailsEndpoint + '/' + email)
remove debug logging?

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +        console.log(ApiClient.requestAccessEndPoint + '?status=Requested')
remove debug logging?

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserAccessApproved.tsx
> +    userDetails: KeyCloakUser[];
We want a single type rather than an array, so `userDetails: KeyCloakUser | undefined`

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserAccessApproved.tsx
> +    userDetails: KeyCloakUser[];
`interface KeyCloakUser` in `UserAccess.tsx` needs an `export` keyword so we can access it here, and the import in this file needs to be: `import {KeyCloakUser} from './UserAccess'`

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserAccessApproved.tsx
> +        <div class="flex-container">
`class` should be `className` here - intellij should show you these issues if you have typescript support

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserAccessApproved.tsx
> +                    <div align="center">Selected User with email {props.userDetails.map(ud => ud.email + ' ')}is granted
once you've fixed the `userDetails` type, you can access it by checking it's defined first, eg {props.userDetails && ...}

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +        <div class="flex-container">
`class` should be `className`

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +interface UserRequestedAccessData {
this needs an `export` keyword so the import in `UserAccess.tsx` will work

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserAccessApprovedList.tsx
> +        console.log(ApiClient.requestAccessEndPoint + '?status=Approved')
remove debug log message

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserAccessApprovedList.tsx
> +    const [count, setCount] = React.useState(0);
let's improve this name, and maybe make it a boolean, eg `userRequested`

2022-10-10 13:16 UTC, richbirch commented on react/src/components/UserManagement/UserAccessApprovedList.tsx
> +    const userRequested = () => {
I think this should be named `requestUser`

2022-10-10 13:16 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/DashboardClient.scala
> +  def postWithRolesAndKeycloakToken(uri: String, roles: Iterable[Role], keyCloakToken: String)(implicit system: ClassicActorSystemProvider): Future[HttpResponse] = {
These two functions are identical apart from the action type. Can we remove the duplication?

2022-10-12 15:45 UTC, ngu04 commented on src/main/scala/uk/gov/homeoffice/drt/notifications/EmailNotifications.scala
> +  def sendAccessGranted(requester: String) = {
couldn't fine bcc feature in gov notify

2022-10-13 11:13 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +    account_type: string;
Can we make this field name format consistent with the others?

2022-10-13 11:13 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +    staff_editing: boolean;
And this one too

2022-10-13 11:22 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/notifications/EmailNotifications.scala
> +    Try(client.sendEmail(
We should probably at least log if this fails

2022-10-13 11:24 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/notifications/EmailNotifications.scala
> +    Try(client.sendEmail(
If there's no bcc/cc option with govnotify, can we send a second copy to our inbox instead. We might not want them in the long run, but initially it'd be good to see that the emails are going out to users and it gives us visibility in case we want to later improve the email wording

2022-10-13 12:09 UTC, ngu04 commented on src/main/scala/uk/gov/homeoffice/drt/notifications/EmailNotifications.scala
> +    Try(client.sendEmail(
I was thinking to do that but was not sure . Know you mention as well , I will do it

2022-10-13 12:56 UTC, richbirch commented on react/src/components/RegionalPort.tsx
> +                <div style={{textAlign:"center"}}><ArrivalExport region={props.region}/></div>
this is changed from left to center. is that intentional?

2022-10-13 12:59 UTC, richbirch approved these changes
:trumpet:

2022-10-13 13:02 UTC, ngu04 commented on react/src/components/RegionalPort.tsx
> +                <div style={{textAlign:"center"}}><ArrivalExport region={props.region}/></div>
good shout , I put to left

2022-10-13 14:22 UTC, merged