Drtii 1099
UKHomeOffice/drt-dashboard pull request #81
Opened 2022-10-28 15:39 UTC by ngu04

multiple user access request
dismiss user access
multiple user access 
fixing single click approval on modal
fixing staff access

2022-10-31 11:28 UTC, richbirch requested changes
Things to rename, and a few types to specify or tidy

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/ConfirmUserAccess.tsx
> +        window.location.reload();
Let's not reload the page. We can just send a request for the latest access requests

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/ConfirmUserAccess.tsx
> +            Following selected users are {props.message} access requested.
```The following users have had their request {props.message}```

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/ConfirmUserAccess.tsx
> +            Selected User with
```{email} has had their request {props.message}```

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/ConfirmUserAccess.tsx
> +                {props.emails.filter(e => e != undefined).map(e =>
How about we store the emails once and pass them to these functions instead of using `filter` 3 times. I'm also not sure why you'd need to check for undefined elements of an array

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +    const [apiRequestListCount, setApiRequestListCount] = React.useState(0);
This looks like it should be a boolean and be called something like `accessRequestListRequested`

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
>      const [showApprovedRequests, setShowApprovedUserRequest] = React.useState("Requested")
This sounds like it's a boolean, but it's not. A clearer name might be `statusFilterValue`

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
>      const getAccessRequest = (response: AxiosResponse) => {
This name is misleading. It's updating the display, not getting anything

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +        console.log('response' + (response.data as KeyCloakUser).email)
Do we need these logs?

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +    const [userDetails, setUserDetails] = React.useState([] as KeyCloakUser[]);
This should not be an array - you're only using a single user's details

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
>      const userRequested = () => {
This name is also misleading. It sounds like a boolean, but it's getting a list of pending requests. Maybe `fetchPendingRequests`

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
>      const [selectedRows, setSelectedRows] = React.useState([]);
This contains the IDs of selected rows, so maybe rename `selectedRowIds`

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +        let fond: any[] = selectedRows.map(s => findEmail(s))
How about you get the email from the users and rename this to describe what it contains, eg `emailAddresses`, then you can pass it directly to the keycloak function

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +    const addSelectedRowDetails = (srd: any) => {
Should this type should be `string` rather than `any`?

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
>      const addSelectedRows = (ids: any) => {
This parameter type should be `string[]`. Then you won't need to check it if's undefined

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
>      const getRow = (email: string) => {
A clearer name would be `findRequestByEmail`

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +        if (getRow((userDetail as KeyCloakUser).email)) {
Save the result of `getRow` so we don't call it again on the next line

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
>      const [requestPosted, setRequestPosted] = React.useState(false)
A clearer name might be `requestApprovalSent`

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +        setApiRequestCount(1)
`apiRequestCount` is not being used apart from in some debugging, so can be removed

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
>          return !props.approvedPage ?
`approvedPage` would be clearer as `showApproveButton`

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +        console.log('keyCloakUserDetails setUserDetails ' + (userDetails as KeyCloakUser))
If you specify the type of `userDetails` where it's defined then we won't need to user `as` where it's being used

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +        console.log('keyCloakUserDetails props.rowDetails?.email ' + props.rowDetails?.email)
do we need these 3 log lines?

2022-10-31 11:28 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +                                            <a href={"mailto:" + props.rowDetails?.email + "?Subject=Access%20grant"}
the subject should probably be `DRT access request` in these links

2022-10-31 12:12 UTC, ngu04 commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +        setApiRequestCount(1)
This is being not just used for debugging

2022-10-31 12:15 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +        setApiRequestCount(1)
Oh yes apologies. It should be a boolean

2022-10-31 12:17 UTC, ngu04 commented on react/src/components/UserManagement/UserAccess.tsx
> +    const [userDetails, setUserDetails] = React.useState([] as KeyCloakUser[]);
This changes is for multiple select user request to work for approval.

2022-10-31 12:20 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +    const [userDetails, setUserDetails] = React.useState([] as KeyCloakUser[]);
Gotcha. Then let's rename it to reflect the fact it's more than one user. Maybe `users` rather than than `userDetails`

2022-10-31 12:52 UTC, ngu04 commented on react/src/components/UserManagement/ConfirmUserAccess.tsx
> +        window.location.reload();
I can do that but I need pass state from `useraccess` to `confirmUserAccess` and with `back` click to reset the state and make latest request for request  . Also this is generic for dismiss and approval so i need to pass state for both and back .  With reload it automatically goes by to default with latest request .

2022-10-31 12:56 UTC, richbirch commented on react/src/components/UserManagement/ConfirmUserAccess.tsx
> +        window.location.reload();
You can do it! We shouldn't ever need to use location.reload in a single page app

2022-11-02 11:01 UTC, ngu04 commented on react/src/components/UserManagement/UserAccess.tsx
>      const addSelectedRows = (ids: any) => {
onSelectionModelChange is not able take string[]

2022-11-02 11:59 UTC, richbirch requested changes
Still a lot of name changes needed here. There are a lot of variable and functions with names that have nothing to do with what they're being used for which makes it really difficult to see what's going on.
I'll also submit a PR against this branch to show how to get rid of the `any` types

2022-11-02 11:59 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +        console.log("inside handle change....")
Probably don't need this log line?

2022-11-02 11:59 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
>      const userRequested = () => {
This should be called something like `requestAccessRequests` to show what it's doing

2022-11-02 11:59 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +    const setUserAccessData = (response: AxiosResponse) => {
This is about access requests, so maybe call it `handleAccessRequestsResponse`

2022-11-02 11:59 UTC, richbirch commented on react/src/components/UserManagement/ConfirmUserAccess.tsx
> +                return "Approved"
These should all be lowercase as that'll fit both places they're being used

2022-11-02 11:59 UTC, richbirch commented on react/src/components/UserManagement/ConfirmUserAccess.tsx
> +    const email = () => {
We shouldn't need to check for undefined values here

2022-11-02 11:59 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
>      const [requestPosted, setRequestPosted] = React.useState(false)
This name should still be changed to clarify what it's value represents

2022-11-02 11:59 UTC, richbirch commented on react/src/components/UserManagement/UserAccessApprovedList.tsx
>      const approvedAccessApi = () => {
This would be better as `requestAccessRequestsWithStatus`, and pass the status in as a parameter

2022-11-02 11:59 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +    const [apiRequested, setApiRequested] = React.useState(false);
I'm struggling to figure out what `apiRequested` represents. I think it really means that some user details have been updated and you want to make another request - it's only set to true after you've received a response to a call for user details. Whatever it means, it really needs a new name to show what its intended effect is

2022-11-02 11:59 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +    const approvedPage = () => {
Why is this function called `approvedPage`? It returns a button!

2022-11-02 11:59 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +    approvedPage: string;
`approvedPage` is not a good name. It appears to hold the status of access requests that should be shown

2022-11-02 12:52 UTC, ngu04 commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +    const [apiRequested, setApiRequested] = React.useState(false);
apiRequested (api request made to get user details) is state to so that user details are called and updated through api in user effect . It may get confusing bcos we pass it to other component and the component can reset it so that api is called again after any update is done by the component for user access request . 
how is `userApiRequested` . Let me know if that make sense .  we can have chat if you prefer it that way

2022-11-02 13:50 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +    const [apiRequested, setApiRequested] = React.useState(false);
If its purpose is to signal that the user should be added to groups then it could be called `readyToAssignGroupsToUser`. Hopefully you see what I mean - `userApiRequested` doesn't really say what it signals (what is the user api that has been requested?)

2022-11-02 16:08 UTC, richbirch requested changes
Nearly there! Just a couple more improvements and probably removing a bunch of logs

2022-11-02 16:08 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +        console.log('rowClickOpen' + userData + ' ' + openModal)
We probably don't need these logs now?

2022-11-02 16:08 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +    const approveUserDetails = () => {
This doesn't approve user details. It fetches user details from keycloak. So maybe name it `fetchUsers`?

2022-11-02 16:08 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +        let email = findRequestByEmail((user as KeyCloakUser).email)
Good to use `const` if we don't want a mutable variable

2022-11-02 16:08 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +        console.log('React.useEffect user details ' + users.length + ' ' + users.map(ud => ud.email))
Do we want this log?

2022-11-02 16:08 UTC, richbirch commented on react/src/components/UserManagement/UserAccess.tsx
> +    }, [users, receivedUserDetails, requestPosted, receivedUsersResponse]);
It looks like you can remove `requestPosted` from the dependencies

2022-11-02 16:08 UTC, richbirch commented on react/src/components/UserManagement/UserRequestDetails.tsx
> +        console.log('keyCloakUserDetails props.rowDetails?.email ' + props.rowDetails?.email)
Do you still want this log?

2022-11-03 09:50 UTC, richbirch approved these changes
Nice one!

2022-11-03 12:24 UTC, merged