Drtii 1158
UKHomeOffice/drt-dashboard pull request #93
Opened 2023-01-16 12:48 UTC by ngu04

- inactivity user access actions for users with no email address 
- adding test using in memory H2 database

2023-01-16 13:52 UTC, richbirch requested changes
Nice - a few changes to make to tidy up and correct what you're testing

2023-01-16 13:52 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/UserDao.scala
> +  def id = column[String]("ID", O.PrimaryKey)
Is this going to be compatible with the existing lowercase column names? Postgres is case-sensitive, so I'd assume this won't work with the exiting tables in preprod and prod

2023-01-16 13:52 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/db/UserDao.scala
> +  def deleteAll()(implicit executionContext: ExecutionContext): Future[Int]
Should we maybe leave these `deleteAll` functions in mocked versions of these classes so they're not accessible to prod code?

2023-01-16 13:52 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/keycloak/KeycloakService.scala
> +  def getUsersForUsername(username: String): Future[Option[KeyCloakUser]] = {
This function is returning a single user, not multiple users

2023-01-16 13:52 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/keycloak/KeycloakService.scala
> +    keycloakClient.getUsersForUsername(username)
Same here - should be renamed to remove the `s`

2023-01-16 13:52 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/schedule/UserTracking.scala
> +        context.log.info("KeyCloakToken-RevokeAccess")
I guess we don't need this log line

2023-01-16 13:52 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/schedule/UserTracking.scala
>        case KeyCloakToken(token: KeyCloakAuthToken) =>
If this actor's primary reason for existence is to revoke access to inactive users then it should probably be renamed to reflect that. At the moment sending a `KeyCloakToken` to this actor results in it sending emails and disabling user accounts, which isn't very obvious given its name.

2023-01-16 13:52 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/schedule/UserTracking.scala
>          Behaviors.same
Rather than sending the actor a `KeyCloakToken` to trigger emails and revoke accounts, it would be nice to use `.ask()` in the `RevokeUserCheck` case and map over the future, sending itself an explicit command like `PerformAccountRevocations(keycloakToken)'. That way the actor behaves in a predictable way

2023-01-16 13:52 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/schedule/UserTracking.scala
> +              keycloakService.getUsersForUsername(utr.username).map { ud =>
this map is almost identical to the one above, so you can extract the common lines to a function

2023-01-16 13:52 UTC, richbirch commented on src/test/scala/uk/gov/homeoffice/drt/db/MockUserDaoSpec.scala
> +  "select all" should "give all users" in {
These test are testing the mock rather than the proper class. You need to move the code in the dao class into a common parent so both the tests and the prod code behave the same

2023-01-16 13:52 UTC, richbirch commented on src/test/scala/uk/gov/homeoffice/drt/db/UserDaoSpec.scala
> +class UserDaoSpec extends Specification with AfterEach with BeforeEach {
Are you planning to remove this set of tests as you have a set testing the same behaviour using mock?

2023-01-16 13:52 UTC, richbirch commented on src/test/scala/uk/gov/homeoffice/drt/db/MockUserDaoSpec.scala
> +  val user3 = User(
Would be nice to name these user variables descriptively so the tests are easier to read, eg `userLastLogin61DaysAgo`

2023-01-16 15:47 UTC, ngu04 commented on src/test/scala/uk/gov/homeoffice/drt/db/UserDaoSpec.scala
> +class UserDaoSpec extends Specification with AfterEach with BeforeEach {
I am thinking to keep this and remove mock .

2023-01-16 15:49 UTC, ngu04 commented on src/main/scala/uk/gov/homeoffice/drt/db/UserDao.scala
> +  def id = column[String]("ID", O.PrimaryKey)
Good point,did testing after H2 test .   I will amend change accordingly  Thanks !

2023-01-19 09:11 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/Server.scala
> +  url: String,
Is there a reason you want to change the indentation style in this file?

2023-01-19 09:12 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/routes/UserRoutes.scala
> +    prefix: String,
Indentation style change here too. Have you changed something in intellij?

2023-01-19 09:13 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/schedule/UserTracking.scala
> +class UserTracking(
Indentation again

2023-01-19 09:23 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/keycloak/KeyCloakAuthTokenService.scala
> +          getManageUserToken(keyClockConfig, manageUsername, managePassword, context).map(PerformAccountRevocations).map(replyTo ! _)
`PerformAccountRevocations` doesn't belong here. The `KeyCloakAuthTokenService` shouldn't know about revoking accounts. It should just return a token in response to the `GetToken` command

2023-01-19 09:25 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/schedule/UserTracking.scala
> +        context.log.info("KeyCloakToken-RevokeAccess")
Can we either remove this log line or change it to mention the command being processed?

2023-01-19 09:27 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/schedule/UserTracking.scala
> +        keycloakServiceBehavior.ask(ref => GetToken(ref)).map(token => context.self ! token)
`GetToken` should reply with a `KeyCloakAuthToken`, which we can then send to our self with the `PerformAccountRevocations` command

2023-01-19 09:31 UTC, ngu04 commented on src/main/scala/uk/gov/homeoffice/drt/Server.scala
> +  url: String,
this is happened by default on my intellij

2023-01-19 09:31 UTC, richbirch commented on src/test/scala/uk/gov/homeoffice/drt/db/MockUserDao.scala
> +      .map(_.filter(u => u.inactive_email_sent.isEmpty && u.latest_login.toLocalDateTime.isBefore(LocalDateTime.now().minusDays(numberOfInactivityDays))))
If you're keeping this mock then you need to move the logic that's common to the prod version into the `IUserDao` so that they share it rather than duplicating. If we changed the prod logic at some point then at the moment you'd need to remember to also change it here

2023-01-19 09:32 UTC, richbirch requested changes
Getting there mate! Just a few more things to fix

2023-01-19 09:33 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/Server.scala
> +  url: String,
Ok. So we've never used this style of indentation. Can you update your intellij settings to match what we usually do?

2023-01-19 09:34 UTC, ngu04 commented on src/test/scala/uk/gov/homeoffice/drt/db/MockUserDao.scala
> +      .map(_.filter(u => u.inactive_email_sent.isEmpty && u.latest_login.toLocalDateTime.isBefore(LocalDateTime.now().minusDays(numberOfInactivityDays))))
I will delete MockUserDao as now we got test covered for it

2023-01-19 11:46 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/schedule/UserTracking.scala
> +                  if (utr.email.toLowerCase.trim == uId.email.toLowerCase.trim) {
This `if` will always be true

2023-01-19 11:46 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/schedule/UserTracking.scala
> +                  if (utr.email.toLowerCase.trim == uId.email.toLowerCase.trim) {
oh sorry I misread it

2023-01-19 11:48 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/schedule/UserTracking.scala
> +                  if (utr.email.toLowerCase.trim == uId.email.toLowerCase.trim) {
would be good to rename these to make it easier to read:
`utr` -> `userToRevoke`
`uId` -> `userFromKeycloak`

2023-01-19 11:54 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/drt/schedule/UserTracking.scala
> +              keycloakService.getUsersForEmail(utr.email).map { ud =>
This is another plural that should be singular `getUserForEmail`

2023-01-19 14:43 UTC, richbirch approved these changes
Nice!

2023-01-19 15:16 UTC, merged